### ISSUE TITLE
Plan for CRAN release

### ISSUE THREAD

**Issue by Kertoo** [ncn-foreigners/singleRcapture#36]
The following list describes changes that are to be made before we can release `singleRcapture` to CRAN:
- [x] Complete plan for 0.2.0.
Add more error messages in:
- [x] Fitting especially `optim`.
- [x] Deviance residuals -> numerical inversion of $\mu(\boldsymbol{\eta})$ function.
- [x] `singleR` class methods.
- [x] Add checks for very low numeric values of weights $(< \varepsilon_{\text{weights}}$ maybe `1e-12` by default) to make `IRLS` more stable.
- [x] Speed up simulate in "new" family functions.
- [x] #40
- [x] `predict` method.
- [x] Examples for `estimate_popsize.fit`.
- [x] Move creation of starting parameters to family functions.
- [x] Standardization of syntax.
- [x] Check for full rank of $\boldsymbol{X}$ matrix, currently it is assumed apriori that $\boldsymbol{X}$ is full rank.
- [x] Standardize factors in exported data frames.

**Comment by Kertoo** [comment]
Update: Plan for `0.2.0` is completed. I'll pull after rest of these points are completed and then submit it to CRAN

**Comment by Kertoo** [comment]
Closing after CRAN submission.
