### ISSUE TITLE
TODO 0.1.0

### ISSUE THREAD

**Issue by BERENZ** [ncn-foreigners/singleRcapture#4]
1. Plan for **0.1.0**

Models:
- [x] zero-truncated Poisson + covariates
- [x] zero-one truncated Poisson + covariates
- [x] zero-truncated Negative Binomial + covariates
- [x] zero-one truncated Negative Binomial + covariates
- [x] Zelterman's estimator + covariates
- [x] Chao's estimator + covariates
- [x] zero-truncaed Geometric + covariates
- [x] zero-one truncaed Geometric + covariates

Estimation methods:
- [x] IRLS
- [x] MLE

Population size estimation:
- [x] Point estimates
- [x] Variance estimator - analytic

Theory:
- [ ] PDF vignette (?)

Datasets: 
- [x] farmsubmission
- [x] carcasssubmission
- [x] netherlandsimmigrant
- [ ] ...

**Comment by Kertoo** [comment]
Expanded plan for 0.2.0

**Comment by BERENZ** [comment]
@Kertoo maybe split it into three issues, separately for 0.2.0 and 0.3.0 ?
