### ISSUE TITLE
TODO 0.3.0

### ISSUE THREAD

**Issue by Kertoo** [ncn-foreigners/singleRcapture#8]
3. Plan for `singleRcapture` version **0.3.0**

Refactor code to make it easier to implement non standard approaches:
- [x]  Subclasses for `singleR` (currently only one for standard implemented frequentist count modelling later add class for bayesian and mixed effects)
- [x] Change methods to adjust for these subclasses
- [x] Make it so that family type objects fully handle data (i.e. with zero one truncated or chao/zelterman)
- [ ] Implement ratio regression

Further diagnostic information:
- [ ] Null deviance
- [x] deviance residuals (for models that do require a paper with theory)
- [ ] ...

Fitting:
- [ ] Bias Reduction compatibility with `brglm2`
- [ ] Robust zero-truncated Poisson #5 
- [ ] Robust zero-truncated Geometric
- [ ] EM algorithm
- [ ] Estimation by full likelihood i.e. not observed likelihood
- [x] Link functions in family functions
- [ ] Additional measures for intercept only models to make them faster

Quality of life improvements:
- [x] Prior weights as population counts
- [ ] Class for multiple models
- [ ] Multithreading (or possibly `julia` backend if it will be easier) in bootstrap and multiplication of $\boldsymbol{W}_{k}$ matrixes with pseudo-residuals and simulation of information information matrixes in negative binomials
- [x] Update the `simulate.singleR` method and create `simulate.singleRfamily`, `update.singleR` methods.
- [ ] Method for variable selection.
- [ ] ...

Compatibility:
- [ ] Method pseudoR2 funcions for `singleR` class

Models:
- [ ] truncated binomial models (inflated hurdle etc)
- [ ] multiple chao
- [ ] one-inflated chao

**Moved to [singleRcaptureExtra](https://github.com/ncn-foreigners/singleRcaptureExtra) package:**
<s>
- Method for pop size estimation for `vglm`
- Method for pop size estimation for `zerotrunc`
</s>
