### ISSUE TITLE
TODO 0.2.0

### ISSUE THREAD

**Issue by Kertoo** [ncn-foreigners/singleRcapture#9]
2. Plan for **0.2.0**

Diagnostics / Influence metrics -> model parameters
- [x] pearson residuals
- [x] deviance residuals (for models that don't require a paper with theory)
- [x] dfbetas 
- influence.measures:
   - [x] cooks.distance
   - [x] hatvalues
- [x] ... 

Sensitivity analysis -> population size 
- [x] dfpopsize 

Functionality and quality of life improvements
- Control parameters for:
   - [x] Regression
   - [x] Population estimate
   - [x] Model
- [x] Subsets and other main function parameters
- [x] ...

Additional models
- [x] zero-truncated one-inflated poisson
- [x] zero-truncated one-inflated negative binomial
- [x] zero-truncated one-inflated geometric
- [x] pseudo-hurdle zero truncated poisson
- [x] pseudo-hurdle zero truncated negative binomial
- [x] pseudo-hurdle zero truncated geometric

Bootstrap estimation of population size variance
- [x] Nonparametric
- [x] Semiparametric
- [x] Fullyparametric

Model Assessment
- [x] G and chi^2 tests

Fitting
- [x] Multi-parameter IRLS

Plots

- [x] Stratification variables

Simple testing with `tinytest`

Proofreading

Website

**Comment by BERENZ** [comment]
@Kertoo provide references for bootstrap

**Comment by Kertoo** [comment]
Zwane, PGM EN and Van der Heijden, Implementing the parametric bootstrap in capture-recapture models with continuous covariates 2003 Statistics & probability letters 65.2 pp 121-125

Norris, James L and Pollock, Kenneth H Including model uncertainty in estimating variances in multiple capture studies 1996 in Environmental and Ecological Statistics 3.3 pp 235-244

**Comment by Kertoo** [comment]
Completed after commit da47e55 this will be on main within two weeks
